apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-ingress
  namespace: account
  labels:
    app: account-service
spec:
  ingressClassName: nginx
  rules:
    - host: account.local
      http:
        paths:
          - path: /api/account
            pathType: Prefix
            backend:
              service:
                name: account-service
                port:
                  number: 80

