apiVersion: v1
kind: Secret
metadata:
  name: account-secret
  namespace: account
  labels:
    app: account-service
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=

