apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authorization-ingress
  namespace: authorization
spec:
  ingressClassName: nginx
  rules:
    - host: auth.local
      http:
        paths:
          - path: /api/authorization
            pathType: Prefix
            backend:
              service:
                name: authorization-app
                port:
                  number: 8087
