apiVersion: v1
kind: Service
metadata:
  name: authorization-app
  namespace: authorization
spec:
  selector:
    app: authorization-app
  ports:
    - name: http
      protocol: TCP
      port: 8087
      targetPort: 8087
    - name: management
      protocol: TCP
      port: 8187
      targetPort: 8187
  type: ClusterIP
