apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: antifraud-ingress
  namespace: antifraud
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: antifraud.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: antifraud-service
                port:
                  number: 80