apiVersion: v1
kind: Secret
metadata:
  name: anti-fraud-secrets
  namespace: anti-fraud
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres-password-123
  DB_NAME: anti_fraud
  SPRING_PROFILES_ACTIVE: k8s

