apiVersion: v1
kind: Service
metadata:
  name: anti-fraud-service
  namespace: anti-fraud
  labels:
    app: anti-fraud
    prometheus.io/scrape: "true"
    prometheus.io/port: "8186"
spec:
  selector:
    app: anti-fraud
    version: v1
  ports:
    - name: http
      port: 80
      targetPort: 8086
      protocol: TCP
    - name: management
      port: 8186
      targetPort: 8186
      protocol: TCP
  type: ClusterIP
