apiVersion: v1
kind: Service
metadata:
  name: antifraud-service
  namespace: antifraud
spec:
  selector:
    app: antifraud
  ports:
    - port: 80
      targetPort: 8086
      name: http
  type: ClusterIP