apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: anti-fraud-monitor
  namespace: anti-fraud
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: anti-fraud
  endpoints:
    - port: management
      path: /api/anti-fraud/actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - anti-fraud
